services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: 
      context: ./backend
      target: runner
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}?schema=public
    depends_on:
      - db

  frontend:
    build: 
      context: ./frontend
      target: production
      args:
        - VITE_TITLE=${VITE_TITLE}
        - VITE_DATE_TIME=${VITE_DATE_TIME}
        - VITE_API_URL=${VITE_API_URL}
        - VITE_MAP_CENTER_LAT=${VITE_MAP_CENTER_LAT}
        - VITE_MAP_CENTER_LNG=${VITE_MAP_CENTER_LNG}
        - VITE_MAP_ZOOM=${VITE_MAP_ZOOM}
        - VITE_ADDRESS_PLACEHOLDER=${VITE_ADDRESS_PLACEHOLDER}
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    ports:
      - "3000:80"
    env_file:
      - ./.env
    depends_on:
      - api      

volumes:
  postgres_data:
