services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: 
      context: ./backend
      target: dev
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}?schema=public
      - FRONTEND_URL=${FRONTEND_URL}
    volumes:
      - ./backend:/app
      - ./shared:/shared # Map it here
      - /app/node_modules # Protects container modules      
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:5173" # Map Windows port 3000 to Vite's 5173
    volumes:
      - ./frontend:/app
      - ./shared:/shared # Map it here
      - /app/node_modules
    environment:
      - VITE_API_URL=${BACKEND_URL}
      - ADDRESS_PLACEHOLDER=${ADDRESS_PLACEHOLDER}
    depends_on:
      - api

volumes:
  postgres_data:
